version: '3'

services:
  
  queue:
    image: redis:alpine
    command: redis-server
    ports:
     - 6379:6379
    volumes:
      - ./docker/cfg/redis/redis.conf:/usr/local/etc/redis/redis.conf

  workers:
    depends_on:
      - queue
    build:
      context: .
      dockerfile: ./docker/Dockerfile.worker
    volumes:
      # - ${VCC_WORKING_DIR}:/data
      - ${VCC_BITSTREAMS_DIR}:/data/Bitstreams
      - ${VCC_REFERENCES_DIR}:/data/ReferenceSequences
      
    environment:
      # - VCC_DISABLE_HDRMETRICS=1
      # - VCC_DISABLE_VMAF=1
      - VMAF_MODEL=/home/deps/vmaf/model/vmaf_v0.6.1.json
      - VCC_WORKING_DIR=/data
      - CELERY_BROKER_URL=redis://queue:6379/0
      - CELERY_RESULT_BACKEND=redis://queue:6379/1

    # command: [ "python3", "-m", "celery", "-A", "vcc", "worker", "--loglevel=info", "--concurrency=2", "-n", "worker@%h"]
    command: [ "/bin/sh", "-c", "pip install debugpy -t /tmp && python3 /tmp/debugpy --listen 0.0.0.0:6900 -m celery -A vcc worker --loglevel=info --concurrency=2 -n worker@%h"]
    ports:
     - 6900:6900
        
  status:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.flower
    depends_on:
      - queue
      - workers
    environment:
      - CELERY_BROKER_URL=redis://queue:6379/0
      - FLOWER_PORT=8888
      - CELERY_SEND_EVENTS=1
    ports:
      - 8888:8888
    volumes:
      - ./docker/cfg/redis/redis.conf:/usr/local/etc/redis/redis.conf
  

